server:
  port: 7777
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lasttest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123123
  redis:
    host: 192.168.136.128
    port: 6379
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml